### ISSUE TITLE
Invalid Token when connecting API

### ISSUE THREAD

**Issue by chrissietowill** [Gladior-B-V/pagespeed-insights-connector#1]
Hi there, I keep getting an error when trying to add my API key. The error is Invalid Token. Can you help resolve?

**Comment by zoedufrenne** [comment]
Hi @chrissietowill , thanks for letting us know. I let development know and keep you updated when the fix is live!

**Comment by zoedufrenne** [comment]
@chrissietowill we fixed the api key generator. Can you let us know if the fix is working?

**Comment by chrissietowill** [comment]
Yes, I have been able to connect ok now. Thanks :-)

Could you tell me how I refresh the data that displays in my Looker Studio board using this connector?

**Comment by zoedufrenne** [comment]
Hi, How do you mean the refresh? When it's connected to looker studio the data should be visible in the dashboard.

**Comment by chrissietowill** [comment]
Hello, thanks for your response. To clarify...when I connected your connector to Looker Studio for the first time, all the data fed in, was accurate and looked great. However when I then logged in following day for example, all the data was the same as it was the day before... however if I run the page speed test externally, the data has changed. This change is not reflected in the results so I was wondering how it works in terms of getting a current page speed test. Is it only set to update a certain time increments? Hope that makes more sense :)

**Comment by zoedufrenne** [comment]
Hi @chrissietowill, The cache is done on our side and you can't empty it. For now it's set on a 30 day cache. Without the cache the connector collects to much data and crash. We have on our roadmap to bring a paid version of the page speed connector where you can empty the cache yourself and keep the cache for x hours.

**Comment by chrissietowill** [comment]
That's great - thanks for the response - it clarifies everything for me. Your help has been much appreciated :)
