### ISSUE TITLE
Update data in google looker studio dashboard

### ISSUE THREAD

**Issue by RecruitersCampus** [Gladior-B-V/pagespeed-insights-connector#2]
Hi, I'm using your PageSpeed Insights Connector for Looker Studio, a few days ago I made the connection but the data that I get is not updated, although it appears within Looker Studio that the data is updated every 12 hours, comparing the report that gives me PageSpeed directly on the website, are not the same results in my dashboard looker studio with connection to DataHub by Gladior. How can I get the data to update?
![data-in-pagespeed-google](https://github.com/Gladior-B-V/pagespeed-insights-connector/assets/143430769/a7424fe9-f4a1-4ff8-842f-81dfc528bc8a)
![select-data-in-google-looker-studio-with-datahub-connector](https://github.com/Gladior-B-V/pagespeed-insights-connector/assets/143430769/fefcf303-1986-472c-a177-4f2d04e77e52)

**Comment by zoedufrenne** [comment]
Hi @RecruitersCampus, can you reconnect the data source and checkbox true for _Allow 'Enter a web page URL' to be modified in reports?_   The request is done when you enter a web page URL. It's always a momentary recording.

**Comment by zoedufrenne** [comment]
There is no way to empty any cache. The cache is done on our side and you can't empty it. For now it's set on a 30 day cache. Without the cache the connector collects to much data and crash.
